# Default values for slate-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# namespace is the Kubernetes namespace where all objects will reside
namespace: 'default'

# dockerImageTag is the tag used to specify a Docker image from OSG Harbor
dockerImageTag: 'xxxx'

# harborProjectID is the project id in OSG Harbor
harborProjectID: 'slate'
# harborRepoHostname is the hostname used by OSG Harbor
harborRepoHostname: 'hub.opensciencegrid.org'



# apiPort is the port for the SLATE API
apiPort: '18080'
# apiTierLabel is the K8s label for the SLATE API
apiTierLabel: 'api'
# apiServerThreads is the number of threads used by the server
apiServerThreads: '128'

# awsLocalImageTag is the image tag for a local dynamodb instance
awsLocalImageTag: '1.18.0'

# emailDomain is the email domain used when sending email
emailDomain: 'slateci.io'

# geocodeEndpoint is the URL used when contacting the geocoding framework
geocodeEndpoint: 'https://geocode.xyz'

# mailgunEndpoint is the DNS name used when contacting the mailgun framework
mailgunEndpoint: 'api.mailgun.net'
