version: '3.8'
services:
  slate_api:
    container_name: slate_api
    image: slate_api_server:local
    command: "/slate/resources/docker/scripts/init.sh"
    depends_on:
      - slate_database
    build:
      context: .
      dockerfile: ./resources/docker/Dockerfile
      target: local-stage
    volumes:
      - ./:/slate
    ports:
      - "18080:18080"
    networks:
      - slateNetwork

  slate_database:
    container_name: slate_database
    image: dwmkerr/dynamodb:latest
    restart: always
    networks:
      - slateNetwork

#  slate_rancher:
#    container_name: slate_rancher
#    image: rancher/k3s:v1.21.11-k3s1-amd64
#    restart: always
#    tty: true
#    privileged: true
#    command: server --https-listen-port 6443 --kube-apiserver-arg service-node-port-range=30000-30100
#    volumes:
#      - /lib/modules:/lib/modules
#      - kubernetes:/etc/rancher
#      - /sys/fs/cgroup:/sys/fs/cgroup:ro
#    networks:
#      - slateNetwork

  slate_testbench:
    container_name: slate_testbench
    image: slate_testbench:local
#    depends_on:
#      - rancher
    build:
      context: .
      dockerfile: ./resources/docker/Testbench.dockerfile
      args:
        helmversion: 3.8.1
        kubectlversion: 1.21.11
        slateapitoken: 5B121807-7D5D-407A-8E22-5F001EF594D4
        slateapiuser: WebPortal
    volumes:
      - ./:/slate
#      - kubernetes:/etc/rancher
    networks:
      - slateNetwork
    tty: true

networks:
  slateNetwork:

#volumes:
#  kubernetes: