
services:
  clionremote:
    container_name: clionremote
    image: "hub.opensciencegrid.org/slate/slate-server-development:1.0.0"
    cap_add:
      - sys_ptrace
    environment:
      BANANA: "Hello world"
    ports:
      - "2222:22"
      - "18080:18080"
    networks:
      - slateNetwork

networks:
  slateNetwork:
