
services:
  clionremote:
    container_name: clionremote
    image: "hub.opensciencegrid.org/slate/slate-server-development:1.0.0"
    depends_on:
      #      - slate_database
      - slate_rancher_server
    cap_add:
      - sys_ptrace
    environment:
      DYNAMODB_JAR: /dynamodb/DynamoDBLocal.jar
      DYNAMODB_LIB: /dynamodb/DynamoDBLocal_lib
      KUBECONFIG: /output/kubeconfig.yaml
      SLATE_SCHEMA_DIR: /tmp/work/resources/api_specification
      TEST_SRC: /tmp/work/test
      VERSION_OVERRIDE: localdev
    ports:
      - "2222:22"
      - "18080:18080"
    volumes:
      #      - dynamodb_lib:/tmp/DynamoDBLocal_lib
      - k3s-output:/output
    networks:
      - slateNetwork

  #  slate_database:
  #    container_name: slate_database
  #    image: amazon/dynamodb-local:1.18.0
  #    working_dir: /home/dynamodblocal
  #    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
  #    volumes:
  #      - dynamodb_data:/home/dynamodblocal/data
  #      - dynamodb_lib:/home/dynamodblocal/DynamoDBLocal_lib
  #    restart: always
  #    user: root
  #    networks:
  #      - slateNetwork

  slate_rancher_agent:
    container_name: slate_rancher_agent
    image: rancher/k3s:v1.24.9-k3s1-amd64
    depends_on:
      - slate_rancher_server
    restart: always
    privileged: true
    command: "agent"
    tmpfs:
      - /run
      - /var/run
    environment:
      - K3S_TOKEN=slatek3s
      - K3S_URL=https://slate_rancher_server:6443
    networks:
      - slateNetwork

  slate_rancher_server:
    container_name: slate_rancher_server
    image: rancher/k3s:v1.24.9-k3s1-amd64
    restart: always
    privileged: true
    command: "server --bind-address slate_rancher_server"
    tmpfs:
      - /run
      - /var/run
    environment:
      - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
      - K3S_KUBECONFIG_MODE=666
      - K3S_TOKEN=slatek3s
    volumes:
      - k3s-output:/output
      - k3s-server:/var/lib/rancher/k3s
    networks:
      - slateNetwork

networks:
  slateNetwork:

volumes:
  #  dynamodb_data:
  #  dynamodb_lib:
  k3s-output:
  k3s-server:
