version: '3.8'
services:
  api:
    container_name: slate_api_server
    image: slate_api_server:local
    command: '/work/resources/docker/scripts/build-start.sh'
    build:
      context: .
      dockerfile: resources/docker/Debug.dockerfile
    ports:
      - 18080:18080
    volumes:
      - ./:/work
    networks:
      - slateNetwork
    tty: true

networks:
  slateNetwork:
