version: '3.8'
services:
  api:
    container_name: slate_api_server
    image: slate_api_server:local
    command: '/slate/resources/docker/scripts/build-start.sh'
    build:
      context: .
      dockerfile: resources/docker/Debug.dockerfile
    ports:
      - 18080:18080
    volumes:
      - ./:/slate
    networks:
      - slateNetwork
    tty: true
  db:
    container_name: slate_database
    image: dwmkerr/dynamodb:latest
    restart: always
    networks:
      - slateNetwork

networks:
  slateNetwork:
