apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-apitoken-secret" (include "helm-slate-api.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-slate-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  api_token: {{ .Values.apiToken }}
