apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-aws-secret" (include "helm-slate-api.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-slate-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  aws_access_key: {{ .Values.awsAccessKey }}
  aws_secret_key: {{ .Values.awsSecretKey }}
