apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-geocode-secret" (include "helm-slate-api.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-slate-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  geocode_token: {{ .Values.geocodeToken }}
