apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-mailgun-secret" (include "helm-slate-api.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "helm-slate-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  mailgun_key: {{ .Values.mailgunKey }}
