apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-aws-secret
  labels:
    stage: {{ .Values.stage }}
type: Opaque
stringData:
  aws_access_key: {{ .Values.awsAccessKey }}
  aws_secret_key: {{ .Values.awsSecretKey }}