---
- name: Check currently installed version of AWS CLI components
  command: >-
    {{ awscli_install_dir}}/aws/dist/aws --version
  register: awscli_current_version
  failed_when: no
  changed_when: no

- name: Set whether missmatch between requested and installed version of AWS CLI
  set_fact:
    awscli_current_missmatch: "{{ (awscli_current_version.stdout | regex_search('aws-cli/' + awscli_version)) != ('aws-cli/' + awscli_version) }}"

- name: Remove existing AWS CLI installation
  file:
    path: '{{ awscli_install_dir }}'
    state: absent
  when: awscli_current_missmatch

- name: Ensure AWS CLI directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - "{{ awscli_install_dir }}"

- name: Copy gpg key for AWS CLI
  copy:
    src: "../files/aws-cli.pubkey"
    dest: "/tmp/aws-cli.pubkey"
    owner: root
    group: root
    mode: 0640
  when: awscli_current_missmatch

- name: Import gpg key for AWS CLI
  command: >-
    gpg --import /tmp/aws-cli.pubkey
  when: awscli_current_missmatch

- name: Download AWS CLI
  get_url:
    url: "{{ awscli_mirror }}/{{ awscli_archive_filename }}"
    dest: /tmp
  when: awscli_current_missmatch

- name: Download AWS CLI signature
  get_url:
    url: "{{ awscli_mirror }}/{{ awscli_archive_filename }}.sig"
    dest: /tmp
  when: awscli_current_missmatch

- name: Verify AWS CLI signature
  command: >-
    cd /tmp
    gpg --verify {{ awscli_archive_filename }}.sig {{ awscli_archive_filename }}
  when: awscli_current_missmatch

- name: Extract AWS CLI download archive
  unarchive:
    src: "/tmp/{{ awscli_archive_filename }}"
    dest: "{{ awscli_install_dir }}"
    remote_src: yes
    owner: root
    group: root
    mode: 0755
  when: awscli_current_missmatch

- name: Delete AWS CLI temporary files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/aws-cli.pubkey"
    - "/tmp/{{ awscli_archive_filename }}"
    - "/tmp/{{ awscli_archive_filename }}.sig"

- name: Create AWS CLI symbolic link
  file:
    src: "{{ awscli_install_dir }}/aws/dist/aws"
    dest: '/usr/local/bin/aws'
    state: link
    owner: root
    group: root
    mode: '0755'

# Resources:
# * https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
