---
- name: Check currently installed version of AWS CLI
  command: >-
    {{ awscli_install_dir}}/aws --version 2>&1 | awk '{ print $1 }'
  register: awscli_current_version
  failed_when: no
  changed_when: no

#- name: Remove existing AWS CLI installation
#  file:
#    path: '{{ awscli_install_dir }}'
#    state: absent
#  when:
#    - awscli_current_version.rc == 0
#    - awscli_current_version.stdout != ('aws-cli/' + awscli_version)
#
#- name: Ensure AWS CLI directories exist
#  file:
#    path: "{{ item }}"
#    state: directory
#    owner: root
#    group: root
#    mode: 0755
#  with_items:
#    - "{{ awscli_install_dir }}"
#
#- name: Copy gpg key for AWS CLI
#  copy:
#    src: "../files/aws-cli.pubkey"
#    dest: "/tmp/aws-cli.pubkey"
#    owner: root
#    group: root
#    mode: 0640
#  when: awscli_current_version.stdout != ('aws-cli/' + awscli_version)
#
#- name: Import gpg key for AWS CLI
#  command: >-
#    gpg --import /tmp/aws-cli.pubkey
#  when: awscli_current_version.stdout != ('aws-cli/' + awscli_version)
#
#- name: Download AWS CLI
#  get_url:
#    url: "{{ awscli_mirror }}/{{ awscli_archive_filename }}"
#    dest: /tmp
#  when: awscli_current_version.stdout != ('aws-cli/' + awscli_version)
#
#- name: Download AWS CLI signature
#  get_url:
#    url: "{{ awscli_mirror }}/{{ awscli_archive_filename }}.sig"
#    dest: /tmp
#  when: awscli_current_version.stdout != ('aws-cli/' + awscli_version)
#
#- name: Verify AWS CLI signature
#  command: >-
#    cd /tmp
#    gpg --verify {{ awscli_archive_filename }}.sig {{ awscli_archive_filename }}
#  when: awscli_current_version.stdout != ('aws-cli/' + awscli_version)
#
#- name: Extract AWS CLI download archive
#  unarchive:
#    src: "/tmp/{{ awscli_archive_filename }}"
#    dest: "{{ awscli_install_dir }}"
#    remote_src: yes
#    owner: root
#    group: root
#    mode: 0755
#  when: awscli_current_version.stdout != ('aws-cli/' + awscli_version)
#
#- name: Delete AWS CLI download archive
#  file:
#    path: "/tmp/{{ awscli_archive_filename }}"
#    state: absent
#  with_items:
#    - "/tmp/aws-cli.pubkey"
#    - "/tmp/{{ awscli_archive_filename }}"
#    - "/tmp/{{ awscli_archive_filename }}.sig"
#
#- name: Create AWS CLI symbolic link
#  file:
#    src: "{{ awscli_install_dir }}/aws"
#    dest: '/usr/local/bin/aws'
#    state: link
#    owner: root
#    group: root
#    mode: '0755'