---
- name: Checking if SLATE cert directory already exists
  stat:
    path: "/etc/ssl/{{ slate_hostname }}"
  register: slate_cert_directory

- name: Ensure SLATE cert directory exists
  file:
    path: "/etc/ssl/{{ slate_hostname }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not slate_cert_directory.stat.exists

- name: Create key pair for the server
  openssl_privatekey:
    path: "{{ slate_certificate.key_file }}"
    size: 2048

- name: Create certificate signing request
  openssl_csr:
    common_name: "slate_api"
    country_name: "US"
    email_address: "slate@slateci.io"
    locality_name: "Salt Lake City"
    organization_name: "University of Utah"
    path: "{{ slate_certificate.chain_file }}"
    subject_alt_name:
      - "DNS:*.{{ slate_hostname }}"
      - "DNS:{{ slate_hostname }}"
    privatekey_path: "{{ slate_certificate.key_file }}"

- name: Create self-signed certificate
  openssl_certificate:
    csr_path: "{{ slate_certificate.chain_file }}"
    path: "{{ slate_certificate.file }}"
    provider: selfsigned
    privatekey_path: "{{ slate_certificate.key_file }}"
  notify: slate_restart_services

# Resources:
# * https://leftasexercise.com/2020/01/30/understanding-tls-certificates-with-nginx-and-ansible-part-i/
