---

- name: Enable firewalld.service
  service:
    name: firewalld
    state: started
    enabled: true

- name: Permit traffic in default zone on port 18080/tcp
  ansible.posix.firewalld:
    port: 18080/tcp
    permanent: yes
    state: enabled
    immediate: yes
