---
- name: Install extra repos via system package manager
  package:
    name:
      - epel-release
    state: present

- name: Install general packages/dependencies via system package manager
  package:
    name:
      - firewalld
      - git
      - python-setuptools
      - python3
      - python3-devel
      - which
    state: present
  when: slate_debug

- name: Install general packages/dependencies via system package manager (live)
  package:
    name:
      - "@development"
      - certbot
      - cronie
      - firewalld
      - git
      - python-setuptools
      - python3
      - python3-devel
      - which
    state: present
  when: not slate_debug
