---
- name: Checking if SLATE install directory already exists
  stat:
    path: "{{ slate_install_dest }}"
  register: slate_install_path

- name: Ensure SLATE install directory exists
  file:
    path: "{{ slate_install_dest }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: not slate_install_path.stat.exists

- name: Add SLATE configuration
  template:
    src: "templates/slate.conf.j2"
    dest: "{{ slate_install_dest }}/slate.conf"
    owner: root
    group: root
    mode: 0644
  notify: slate_restart_services

