apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-slate-conf-configmap
  namespace: {{ .Values.namespace }}
  labels:
    tier: api
    stage: {{ .Values.stage }}
data:
  slate.conf: |
    allowAdHocApps={{ .Values.allowAdHocApps }}
    appLoggingServerName={{ .Values.appLoggingServerName }}
    appLoggingServerPort={{ .Values.appLoggingServerPort }}
    awsEndpoint={{ .Values.awsEndpoint }}
    awsRegion={{ .Values.awsRegion }}
    awsURLScheme={{ .Values.awsURLScheme }}
    bootstrapUserFile=/slate/slate_portal_user
    emailDomain={{ .Values.emailDomain }}
    encryptionKeyFile=/slate/encryptionKey
    geocodeEndpoint={{ .Values.geocodeEndpoint }}
    mailgunEndpoint={{ .Values.mailgunEndpoint }}
    port={{ .Values.apiPort }}
    sslCertificate=/etc/ssl/fullchain.crt
    sslKey=/etc/ssl/privkey.key
    threads={{ .Values.apiServerThreads }}
