name: SLATE Build Setup
description: Sets up the OS and installs dependencies. Currently only used for Ubuntu since everything else is containerized.

inputs:
  aws_cpp_sdk_version:
    description: The version of the AWS C++ SDK to use, e.g. 1.9.365.
    required: false
    default: 1.9.365
  opentelemetry_version:
    description: The version of the OpenTelemetry C++ client to use, e.g. 1.6.1.
    required: false
    default: 1.6.1

runs:
  using: composite

  steps:
    - name: Check Host
      run: |-
        ID_LIKE=$(awk -F= '$1=="ID_LIKE" { print $2 ;}' /etc/os-release)
        if [[ "${ID_LIKE}" ==  *"debian"* ]]
        then
          echo "Host is Debian-based. Proceeding..."
        else
          echo "Host must be Debian-based!"
          exit 1
        fi
      shell: bash

    - name: Install OS Packages
      run: |-
        apt-get update -y
        apt-get install -y \
          autoconf \
          build-essential \
          ccache \
          cmake \
          curl \
          git \
          g++ \
          libbenchmark-dev \
          libboost-all-dev \
          libcrypto++-dev \
          libcurl4-openssl-dev \
          libgmock-dev \
          libgrpc-dev \
          libgrpc++-dev \
          libgtest-dev \
          libprotobuf-dev \
          libtool \
          libssl-dev \
          libyaml-cpp-dev \
          libz-dev \
          pkg-config \
          protobuf-compiler-grpc
      shell: sh

    - name: Install AWS C++ SDK
      working-directory: .
      run: |-
        curl -fsSL https://raw.githubusercontent.com/slateci/docker-images/master/slate-client-server/scripts/install-aws-cpp-sdk.sh -o install-aws-cpp-sdk.sh
        chmod +x ./install-aws-cpp-sdk.sh
        ./install-aws-cpp-sdk.sh ${{ inputs.aws_cpp_sdk_version }} ubuntu22_04
      shell: sh

    - name: Install OpenTelemetry C++ Client
      working-directory: .
      run: |-
        curl -fsSL https://raw.githubusercontent.com/slateci/docker-images/master/slate-client-server/scripts/install-opentelemetry.sh -o install-opentelemetry.sh
        chmod +x ./install-opentelemetry.sh
        ./install-opentelemetry.sh ${{ inputs.opentelemetry_version }} ubuntu22_04
      shell: sh
