apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-slate-database
  namespace: {{ .Values.namespace }}
  labels:
    tier: {{ .Values.tierLabels.database }}
    stage: {{ .Values.stage }}
spec:
  replicas: {{ .Values.databaseReplicaCount }}
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      tier: {{ .Values.tierLabels.database }}
      stage: {{ .Values.stage }}
  template:
    metadata:
      labels:
        tier: {{ .Values.tierLabels.database }}
        stage: {{ .Values.stage }}
    spec:
      containers:
        - name: slate-database
          image: "amazon/dynamodb-local:{{ .Values.databaseImageTag }}"
          imagePullPolicy: IfNotPresent
          workingDir: /home/dynamodblocal
          command:
            - "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
          ports:
            - containerPort: {{ .Values.databasePort }}
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: {{ .Values.databasePort }}
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 1
          readinessProbe:
            tcpSocket:
              port: {{ .Values.databasePort }}
            initialDelaySeconds: 5
            periodSeconds: 3
            successThreshold: 1
            failureThreshold: 2
            timeoutSeconds: 1
          volumeMounts:
            - name: dynamodb-storage
              mountPath: /data
              subPath: data
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsGroup: 1000
            runAsUser: 1000
            capabilities:
             drop:
               - ALL
             add:
               - NET_BIND_SERVICE
               - SYS_TIME
      restartPolicy: Always
      volumes:
        - name: dynamodb-storage
          emptyDir: {}
