---
- hosts: all
  become: yes
  become_user: root

  pre_tasks:
    - name: Set SSL certs path
      set_fact:
        slate_certificate:
          file: "/etc/ssl/{{ slate_hostname }}/{{ slate_hostname }}.pem"
          key_file: "/etc/ssl/{{ slate_hostname }}/{{ slate_hostname }}.key"
          chain_file: "/etc/ssl/{{ slate_hostname }}/{{ slate_hostname }}.csr"

  tasks:
    - name: OS Packages
      include_tasks: "./tasks/os-packages.yml"

    - name: Firewall
      include_tasks: "./tasks/firewalld.yml"

    - name: SELinux
      include_tasks: "./tasks/selinux.yml"

    - name: Setting Ansible Python Interpreter to Python3
      set_fact:
        ansible_python_interpreter: "/bin/python3"

    - name: Pip
      include_tasks: "./tasks/pip.yml"

    - name: Self-signed Certificates
      include_tasks: "./tasks/certs-selfsigned.yml"

    - name: Local DynamoDB
      include_tasks: "./tasks/dynamodb.yml"
      when: '"localhost" in slate_aws_endpoint'

    - name: Helm3
      include_tasks: "./tasks/helm3.yml"

    - name: AWS CLI
      include_tasks: "./tasks/aws-cli.yml"

#    - name: SLATE API
#      include_tasks: "./tasks/slate.yml"

  handlers:
    - name: Force systemd to re-read configs
      systemd:
        daemon_reload: yes
      listen: systemd_daemon_reload

    - name: Restart dynamodb.service
      service:
        name: dynamodb
        state: restarted
      listen: dynamodb_restart_services

    - name: Restart slate-client-server.service
      service:
        name: slate-client-server
        state: restarted
      listen: slate_restart_services