
{{- if eq .Release.Namespace "local"}}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: "slate-dynamodb-local-pv"
  labels:
    app.kubernetes.io/instance: slate-dynamodb-local
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: slate-dynamodb
    app.kubernetes.io/version: "1.18.0"
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 3Gi
  hostPath:
    path: "/data/slate-dynamodb-local-pv/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "slate-dynamodb-local-pvc"
  labels:
    app.kubernetes.io/instance: slate-dynamodb-local
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: slate-dynamodb
    app.kubernetes.io/version: "1.18.0"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "slate-dynamodb-local-deployment"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: slate-dynamodb-local
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: slate-dynamodb
    app.kubernetes.io/version: "1.18.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: slate-dynamodb-local
      app.kubernetes.io/name: slate-dynamodb
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: slate-dynamodb-local
        app.kubernetes.io/managed-by: {{ $.Release.Service }}
        app.kubernetes.io/name: slate-dynamodb
        app.kubernetes.io/version: latest
    spec:
      containers:
        - name: slate-dynamodb
          image: "amazon/dynamodb-local:1.18.0"
          imagePullPolicy: Always
          workingDir: /home/dynamodblocal
          command:
            - "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
          ports:
            - containerPort: 8000
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            tcpSocket:
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 1

---

apiVersion: v1
kind: Service
metadata:
  name: "slate-dynamodb-local-service"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: slate-dynamodb-local
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    app.kubernetes.io/name: slate-dynamodb
    app.kubernetes.io/version: "1.18.0"
spec:
  type: ClusterIP
  ports:
    - port: 8082
      name: dynamodb-port
      protocol: TCP
      targetPort: 8000
  selector:
    app.kubernetes.io/instance: slate-dynamodb-local
    app.kubernetes.io/name: slate-dynamodb

{{- end }}
