name: "Deploy: SLATE Remote Client"

on:
  push:
    tags:
      - 'v*'

jobs:
  workflow-props:
    name: Workflow Properties
    runs-on: ubuntu-20.04

    steps:
      - name: Store Workflow Properties
        working-directory: .
        run: |-
          echo "## Release Version" >> $GITHUB_STEP_SUMMARY
          echo "${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY

          echo "releaseVersion=${{ github.ref_name }}" >> workflow.properties

      - name: Upload Workflow Properties
        uses: actions/upload-artifact@v3
        with:
          name: shared-workflow-props
          path: ./workflow.properties
          if-no-files-found: error
          retention-days: 1

  client-release:
    name: SLATE Remote Client Release
    needs:
      - workflow-props
    uses: slateci/github-actions/.github/workflows/slate-client-release.yml@feature/86-write-a-re-usable-workflow-for-the-slate-client-github-deployment

  notifications:
    name: Notifications
    runs-on: ubuntu-20.04
    needs:
      - workflow-props
      - client-release
    if: ${{ always() && (needs.workflow-props.result == 'failure' || needs.client-release.result == 'failure') }}

    steps:
      - name: Notify Slack of Failure
        uses: slateci/github-actions/.github/actions/slack-notify-failure@v8
        with:
          slack_bot_token: '${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}'
