name: Development SLATE Service workflow

on:
  push:
    branches: [ 176_build-slate-services-with-github-actions ]

jobs:
  slate-service:
    name: SLATE Service
    runs-on: ubuntu-20.04
    container:
      image: hub.opensciencegrid.org/slate/slate-client-server:1.0.0

    steps:
      - name: Checking out repo...
        uses: actions/checkout@v2

      - name: Build slate-service...
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake3 .. -DBUILD_CLIENT=False -DBUILD_SERVER=True -DBUILD_SERVER_TESTS=True -DSTATIC_CLIENT=False
          make
          ls -al
          pwd

      - name: Create tarball...
        working-directory: ${{ github.workspace }}/build
        run: |
          tar -czvf slate-service.tar.gz slate-service
          ls -al
          pwd

      - name: Create hash of tarball...
        working-directory: ${{ github.workspace }}/build
        run: |
          shasum -b -a 256 slate-service.tar.gz > slate-service.sha256
          ls -al
          pwd

      - name: Persist built binary and hash
        uses: actions/upload-artifact@v2
        with:
          name: "slate-service-artifact"
          path: |
            ${{ github.workspace }}/build/slate-service.tar.gz
            ${{ github.workspace }}/build/slate-service.sha256
          retention-days: 1