name: "Docker: Lint and Scan"

on:
  push:
    branches:
      - banana
#      - develop
#      - master
#    paths:
#      - .github/workflows/docker-lint-scan.yml
#      - resources/docker/**

env:
  DOCKER_TAG: slate-api:local

jobs:
  build:
    name: Build Dockerfile
    runs-on: ubuntu-20.04

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Check out repo
        uses: actions/checkout@v3

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          outputs: type=docker,dest=/tmp/image.tar
          tags: ${{ env.DOCKER_TAG }}

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: image
          path: /tmp/image.tar

  lint:
    name: Lint Dockerfile
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/image.tar

      - name: Lint with Dockle
        uses: hands-lab/dockle-action@v1
        with:
          image: ${{ env.DOCKER_TAG }}
          exit-code: '1'
          exit-level: FATAL

  scan:
    name: Scan Dockerfile
    runs-on: ubuntu-20.04
    needs: build

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: image
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/image.tar

      - name: Scan with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.DOCKER_TAG }}
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'
