name: Build OpenTelemetry C++ Client
concurrency:
  group: otel-${{ github.repository }}

on:
  workflow_dispatch:
    inputs:
      otel_cpp_client_version:
        description: The version of the OpenTelemetry C++ client to build.
        required: false
        default: 1.6.1
        type: string

jobs:
  workflow-inputs:
    name: Display Workflow Inputs
    runs-on: ubuntu-20.04

    steps:
      - name: Output inputs
        run: |-
          echo "## Workflow inputs" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ toJSON(github.event.inputs) }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  build-el:
    name: Build on EL
    runs-on: ubuntu-20.04
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: rockylinux:9
            file-prefix: rocky9

    steps:
      - name: Install OS Packages
        run: |-
          dnf install -y dnf-plugins-core
          dnf config-manager --set-enabled crb -y
          dnf install -y \
            https://dl.fedoraproject.org/pub/epel/epel-release-latest-9.noarch.rpm \
            https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-9.noarch.rpm
          dnf install -y \
            boost-devel \
            cmake3 \
            cryptopp \
            gcc-c++.x86_64 \
            git \
            gmock \
            gmock-devel \
            google-benchmark \
            google-benchmark-devel \
            gtest \
            gtest-devel \
            json-devel \
            libcurl \
            libcurl-devel \
            make \
            openssl \
            openssl-devel \
            perl-Digest-SHA \
            procps-ng \
            protobuf-devel \
            protobuf-compiler \
            strace \
            unzip \
            yaml-cpp-devel \
            zlib-devel

      - name: Create extra directories
        working-directory: .
        run: |-
          mkdir -p ./otel/build
          mkdir -p ./otel/install-artifacts

      - name: Build/install from source
        working-directory: ./otel
        run: |-
          git clone https://github.com/open-telemetry/opentelemetry-cpp.git
          cd opentelemetry-cpp
          git submodule update --init --recursive
          git checkout tags/v${{ github.event.inputs.otel_cpp_client_version }}
          cd ../build
          cmake3 ../opentelemetry-cpp \
            -DBUILD_SHARED_LIBS=Off \
            -DCMAKE_INSTALL_PREFIX=../install-artifacts \
            -DCMAKE_PREFIX_PATH=${{ github.workspace }}/otel/opentelemetry-cpp \
            -DWITH_OTLP=ON
          make
          make install

      - name: Create tarball
        working-directory: ./otel
        run: |-
          ls -al ./install-artifacts/
          tar -czvf ${{ matrix.file-prefix }}-${{ github.event.inputs.otel_cpp_client_version }}.tar.gz ./install-artifacts/
          ls -al
          mv ${{ matrix.file-prefix }}-${{ github.event.inputs.otel_cpp_client_version }}.tar.gz ../

      - name: Persist built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.file-prefix }}
          path: |-
            ./${{ matrix.file-prefix }}-${{ github.event.inputs.otel_cpp_client_version }}.tar.gz
          retention-days: 1

  build-ubuntu:
    name: Build on Ubuntu
    runs-on: ${{ matrix.distro }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - distro: ubuntu-22.04
            file-prefix: ubuntu22_04

    steps:
      - name: Install OS Packages
        run: |-
          sudo apt-get update -y
          sudo apt-get install -y \
            autoconf \
            build-essential \
            cmake \
            g++ \
            libbenchmark-dev \
            libboost-all-dev \
            libcrypto++-dev \
            libcurl4-openssl-dev \
            libgmock-dev \
            libgrpc-dev \
            libgrpc++-dev \
            libgtest-dev \
            libprotobuf-dev \
            libtool \
            libssl-dev \
            libyaml-cpp-dev \
            libz-dev \
            pkg-config \
            protobuf-compiler-grpc

      - name: Create extra directories
        working-directory: .
        run: |-
          mkdir -p ./otel/build
          mkdir -p ./otel/install-artifacts

      - name: Build/install from source
        working-directory: ./otel
        run: |-
          git clone https://github.com/open-telemetry/opentelemetry-cpp.git
          cd opentelemetry-cpp
          git submodule update --init --recursive
          git checkout tags/v${{ github.event.inputs.otel_cpp_client_version }}
          cd ../build
          cmake ../opentelemetry-cpp \
            -DBUILD_SHARED_LIBS=Off \
            -DCMAKE_INSTALL_PREFIX=../install-artifacts \
            -DCMAKE_PREFIX_PATH=${{ github.workspace }}/otel/opentelemetry-cpp \
            -DWITH_OTLP=ON
          make
          make install

      - name: Create tarball
        working-directory: ./otel
        run: |-
          ls -al ./install-artifacts/
          tar -czvf ${{ matrix.file-prefix }}-${{ github.event.inputs.otel_cpp_client_version }}.tar.gz ./install-artifacts/
          ls -al
          mv ${{ matrix.file-prefix }}-${{ github.event.inputs.otel_cpp_client_version }}.tar.gz ../

      - name: Persist built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.file-prefix }}
          path: |-
            ./${{ matrix.file-prefix }}-${{ github.event.inputs.otel_cpp_client_version }}.tar.gz
          retention-days: 1

  deploy:
    name: Deploy to GitHub
    runs-on: ubuntu-20.04
    needs:
      - build-el
      - build-ubuntu

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download Rocky 9 Build
        uses: actions/download-artifact@v3
        with:
          name: rocky9
          path: .

      - name: Download Ubuntu 22.04 Build
        uses: actions/download-artifact@v3
        with:
          name: ubuntu22_04
          path: .

      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ./checkout
          ref: gh-pages

      - name: Configure Git
        uses: slateci/github-actions/.github/actions/configure-git@v12

      - name: Commit artifacts
        working-directory: ./checkout
        run: |-
          for DISTRIBUTION in rocky9 ubuntu22_04
          do
            cp ../$DISTRIBUTION-${{ github.event.inputs.otel_cpp_client_version }}.tar.gz ./opentelemetry-cpp/
          done
          
          git add --all
          git commit -m '(github-action) Added OpenTelemetry C++ Client ${{ github.event.inputs.otel_cpp_client_version }} artifacts.'
          git push
          
          echo "Download artifacts from [https://slateci.io/slate-client-server/](https://slateci.io/slate-client-server/) once the GitHub pages action is complete." >> $GITHUB_STEP_SUMMARY
