name: "Pull Request Checks (Client)"
concurrency:
  group: prc-client-${{ github.repository }}-${{ github.ref }}

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "resources/chart/**"
      - "resources/docs/**"

jobs:
  build-client:
    name: Build Remote Client
    uses: slateci/github-actions/.github/workflows/slate-client-build.yml@v16
