name: "Pull Request Checks (Image)"
concurrency:
  group: prc-image-${{ github.repository }}-${{ github.ref }}

on:
  push:
    branches:
      - banana
      - 392-develop-slate-build-cache-github-workflow
  pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - ".github/**"
      - "resources/chart/**"
      - "resources/docs/**"

jobs:
  lint-scan:
    name: Lint/scan image
    uses: slateci/github-actions/.github/workflows/image-lint-scan.yml@108-add-buildx-cache-support-for-image-related-workflows
    with:
      file: ./resources/docker/Dockerfile
