name: "Pull Request Checks (Image)"
concurrency:
  group: prc-image-${{ github.repository }}-${{ github.ref }}

on:
  pull_request:
    branches:
      - develop
      - master
    paths-ignore:
      - ".github/**"
      - "resources/chart/**"
      - "resources/docs/**"

jobs:
  lint-scan:
    name: Lint/scan image
    uses: slateci/github-actions/.github/workflows/image-lint-scan.yml@v16
    with:
      file: ./resources/docker/Dockerfile
