name: Push to master - Build SLATE Client on macOS

on:
  push:
    branches:
      - master

jobs:
  build-macos:
    runs-on: macos-latest

    steps:
      - name: Clone repo with SVN
        run: svn co -q https://github.com/slateci/slate-client-server/trunk slate-client-server

      - name: Cache object files
        id: cache
        uses: actions/cache@v2
        with:
          path: slate-client-server/build
          key: slate-client-server-${{ runner.os }}-object-files

      - name: Get SVN version
        id: svnversion
        shell: bash
        working-directory: slate-client-server
        run: echo "::set-output name=version::$(svnversion)"

      - name: Run CMake
        working-directory: slate-client-server/build
        run: cmake .. -DSTATIC_CLIENT=True -DBUILD_SERVER=False ..

      - name: Run make
        shell: bash
        working-directory: slate-client-server/build
        run: VERSION=${{ steps.svnversion.outputs.version }} make

      - name: Strip symbols from binary
        working-directory: slate-client-server/build
        run: strip slate

      - name: Create tarball
        working-directory: slate-client-server/build
        run: tar -czvf slate-macos.tar.gz slate

      - name: Generate hash of tarball
        working-directory: slate-client-server/build
        run: shasum -b -a 256 slate-macos.tar.gz > slate-macos.sha256

      - name: Persist built binary and hash
        uses: actions/upload-artifact@v2
        with:
          name: "slate-macos-${{ steps.svnversion.outputs.version }}-artifact"
          path: |
            slate-client-server/build/slate-macos.tar.gz
            slate-client-server/build/slate-macos.sha256
          retention-days: 1
