name: SLATE API Image Workflow

on:
  push:
    branches:
      - feature/178_implement-api-server-as-container

jobs:
  build-push:
    name: Build/Push Image
    runs-on: ubuntu-20.04

    steps:
      - name: Checking out repo...
        uses: actions/checkout@v2

      - name: Set up Docker Buildx...
        uses: docker/setup-buildx-action@v1

      - name: Login to OSG Harbor...
        run: echo '${{ secrets.OSG_HARBOR_PASSWORD }}' | docker login https://hub.opensciencegrid.org -u '${{ secrets.OSG_HARBOR_USERNAME }}' --password-stdin

      - name: Build and push to OSG Harbor...
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./resources/docker/Dockerfile
          target: release-stage
          push: true
          tags: hub.opensciencegrid.org/slate/slate-api:github-${{ github.run_number }}
