name: SLATE API Image Workflow

on:
  push:
    branches:
      - feature/178_implement-api-server-as-container

jobs:
  build-push:
    name: Build/Push Image
    runs-on: ubuntu-20.04

    steps:
      - name: echo default env vars...
        run: |
          echo "Home: ${HOME}"
          echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
          echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
          echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REF: ${GITHUB_REF}"
          echo "GITHUB_RUN_NUMBER: ${GITHUB_RUN_NUMBER}"
          echo "Proposed image tag: ${{ env.BOB }}"

      - name: Checking out repo...
        uses: actions/checkout@v2

      - name: Set up Docker Buildx...
        uses: docker/setup-buildx-action@v1

      - name: Login to OSG Harbor...
        run: echo '${{ secrets.OSG_HARBOR_PASSWORD }}' | docker login https://hub.opensciencegrid.org -u '${{ secrets.OSG_HARBOR_USERNAME }}' --password-stdin

      - name: Build and push...
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./resources/docker/Dockerfile
          target: release-stage
          push: false
          tags: hub.opensciencegrid.org/slate/slate-api:github-${{ github.run_number }}

      - name: Echo
        run: docker image ls