name: SLATE Build Cache
concurrency:
  group: sbcache-${{ github.repository }}

on:
  push:
    branches:
      - banana
#      - 392-develop-slate-build-cache-github-workflow
#  workflow_dispatch:
#    inputs:
#      confirm:
#        description: 'Type "CONFIRM" to build the caches.'
#        required: true
#        type: string

jobs:
#  workflow-inputs:
#    name: Display Workflow Inputs
#    if: ${{ github.event.inputs.confirm == 'CONFIRM' }}
#    runs-on: ubuntu-20.04
#
#    steps:
#      - name: Output inputs
#        run: |-
#          echo "## Workflow inputs" >> $GITHUB_STEP_SUMMARY
#          echo '```' >> $GITHUB_STEP_SUMMARY
#          echo "${{ toJSON(github.event.inputs) }}" >> $GITHUB_STEP_SUMMARY
#          echo '```' >> $GITHUB_STEP_SUMMARY

  build-server-linux:
    name: Build Linux Servers
#    if: ${{ github.event.inputs.confirm == 'CONFIRM' }}
    runs-on: ubuntu-20.04
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - container: hub.opensciencegrid.org/slate/slate-client-server:2.1.0
            file-prefix: rocky9

    env:
      FILE_NAME: ${{ matrix.file-prefix }}-slate-service

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ./checkout
#          ref: master

      - name: Build slate-service tests and binary
        working-directory: ./checkout/build
        run: |-
          cmake3 .. -DBUILD_CLIENT=False -DBUILD_SERVER=True -DBUILD_SERVER_TESTS=True -DSTATIC_CLIENT=False
          export VERSION_OVERRIDE=cache
          make -k

      - name: Create tarball
        working-directory: ./checkout
        run: |-
          ls -al ./build/
          tar -czvf ${{ env.FILE_NAME }}.tar.gz ./build/
          ls -al
          mv ${{ env.FILE_NAME }}.tar.gz ../

      - name: Persist built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.FILE_NAME }}
          path: |-
            ./${{ env.FILE_NAME }}.tar.gz
          retention-days: 1

  deploy:
    name: Deploy to GitHub
    runs-on: ubuntu-20.04
    needs:
      - build-server-linux

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Download Rocky 9 Build
        uses: actions/download-artifact@v3
        with:
          name: rocky9-slate-service
          path: .

      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          path: ./checkout
          ref: gh-pages

      - name: Configure Git
        uses: slateci/github-actions/.github/actions/configure-git@v11

      - name: Commit artifacts
        working-directory: ./checkout
        run: |-
          for DISTRIBUTION in rocky9
          do
            cp ../$DISTRIBUTION-slate-service.tar.gz ./slate-service/
          done
          
          git add --all
          git commit -m '(github-action) Added slate-service artifacts.'
          git push
          
          echo "Download artifacts from [https://slateci.io/slate-client-server/](https://slateci.io/slate-client-server/) once the GitHub pages action is complete." >> $GITHUB_STEP_SUMMARY
