name: "Build/push: Harbor SLATE API"

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Enter the name of image source branch.'
        required: true
        default: develop

      confirm:
        description: 'Type "CONFIRM" to push the SLATE API image to Harbor.'
        required: true

env:
  IMAGE_TAG: hub.opensciencegrid.org/slate/slate-api:github-${{ github.run_number }}

jobs:
  build-push:
    name: Build and push image to OSG Harbor
    runs-on: ubuntu-20.04
    if: ${{ github.event.inputs.confirm == 'CONFIRM' }}

    steps:
      - name: Checking out repo...
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Docker Buildx...
        uses: docker/setup-buildx-action@v1

      - name: Login to OSG Harbor...
        run: echo '${{ secrets.OSG_HARBOR_PASSWORD }}' | docker login https://hub.opensciencegrid.org -u '${{ secrets.OSG_HARBOR_USERNAME }}' --password-stdin

      - name: Build and push to OSG Harbor...
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./resources/docker/Dockerfile
          target: release-stage
          push: true
          tags: ${{ env.IMAGE_TAG }}
