name: Development SLATE Service workflow

on:
  push:
    branches:
      - develop

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container:
      image: hub.opensciencegrid.org/slate/slate-client-server:1.0.1

    steps:
      - name: Checking out repo...
        uses: actions/checkout@v2

      - name: Build slate-service...
        working-directory: ${{ github.workspace }}/build
        run: |
          cmake3 .. -DBUILD_CLIENT=False -DBUILD_SERVER=True -DBUILD_SERVER_TESTS=True -DSTATIC_CLIENT=False
          make

#      - name: Create tarball...
#        working-directory: ${{ github.workspace }}/build
#        run: tar -czvf slate-service.tar.gz slate-service
#
#      - name: Create hash of tarball...
#        working-directory: ${{ github.workspace }}/build
#        run: shasum -b -a 256 slate-service.tar.gz > slate-service.sha256

      - name: Persist built binary...
        uses: actions/upload-artifact@v2
        with:
          name: binary-artifact
          path: |
            build/slate-service
#            ${{ github.workspace }}/build/slate-service.tar.gz
#            ${{ github.workspace }}/build/slate-service.sha256
          retention-days: 1
          if-no-files-found: error

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-20.04

    steps:
      - name: Download built binary...
        uses: actions/download-artifact@v3
        with:
          name: binary-artifact

      - name: List directory workspace contents...
        run: |
          pwd
          ls -al