name: "SLATE API: Development"

on:
  push:
    branches:
      - feature/178_implement-api-server-as-container


#on:
#  workflow_dispatch:
#    inputs:
#      confirm:
#        description: 'Type "CONFIRM" to deploy the SLATE API server to the development environment'
#        required: true

env:
  IMAGE_TAG: hub.opensciencegrid.org/slate/slate-api:github-${{ github.run_number }}

jobs:
  build-push:
    name: Build and push image to OSG Harbor
    runs-on: ubuntu-20.04
#    if: ${{ github.event.inputs.clowntown == 'CONFIRM' }}

    steps:
      - name: Checking out repo...
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: feature/178_implement-api-server-as-container

      - name: Set up Docker Buildx...
        uses: docker/setup-buildx-action@v1

      - name: Login to OSG Harbor...
        run: echo '${{ secrets.OSG_HARBOR_PASSWORD }}' | docker login https://hub.opensciencegrid.org -u '${{ secrets.OSG_HARBOR_USERNAME }}' --password-stdin

      - name: Build and push to OSG Harbor...
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./resources/docker/Dockerfile
          target: release-stage
          push: true
          tags: ${{ env.IMAGE_TAG }}

  deploy:
    name: Deploy to UC Kubernetes
    runs-on: ubuntu-20.04
#    if: ${{ github.event.inputs.clowntown == 'CONFIRM' }}
    needs: build-push

    steps:
      - name: Checking out repo...
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: develop

#      - name:
#        uses: 'deliverybot/helm@v1'
#        with:
#          <blah: https://github.com/marketplace/actions/helm-deploy />
