name: Unit Tests

on:
  push:
    branches:
      - feature/250_new-github-workflow-for-api-unit-tests

#  workflow_dispatch:
#    inputs:
#      branch:
#        description: 'Choose a branch to test:'
#        type: choice
#        default: master
#        options:
#          - develop
#          - master
#        required: true

env:
  MINIKUBE_VERSION: 1.24.0
  KUBERNETES_VERSION: v1.23.1
  PYTHON_VERSION: 3.10

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    container: hub.opensciencegrid.org/slate/slate-client-server:1.0.7

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: .

      - name: Run CMake
        working-directory: ./build
        run: |-
          cmake3 .. -DBUILD_CLIENT=False -DBUILD_SERVER=True -DBUILD_SERVER_TESTS=True -DSTATIC_CLIENT=False

      - name: Run make
        working-directory: ./build
        run: |-
          export VERSION_OVERRIDE=localdev
          make
          ls -al

      - name: Create build tarball
        working-directory: .
        run: |-
          tar -czvf slate-artifacts.tar.gz build

      - name: Persist built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: slate-artifacts
          path: |-
            ./slate-artifacts.tar.gz
          retention-days: 1

  test:
    name: Test
    runs-on: ubuntu-20.04
    needs:
      - build

    steps:
      - name: Download built artifacts
        uses: actions/download-artifact@v3
        with:
          name: slate-artifacts
          path: .

      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./checkout

      - name: Extract built artifacts
        working-directory: .
        run: |-
          tar -zxf slate-artifacts.tar.gz --directory ./checkout
          ls -al ./checkout/build

      - id: minikube
        name: Create Minikube Cluster
        uses: medyagh/setup-minikube@master
        with:
          minikube-version: ${{ env.MINIKUBE_VERSION }}
          driver: docker
          container-runtime: containerd
          kubernetes-version: ${{ env.KUBERNETES_VERSION }}
          cni: calico

      - name: Export Kubeconfig
        working-directory: .
        run: |-
          kubectl config view > kubeconfig
          cat kubeconfig

      - name: Download DynamoDB
        working-directory: .
        run: |-
          echo "Downloading DynamoDB from Amazon......................."
          for FILENAME in dynamodb_local_latest.tar.gz dynamodb_local_latest.tar.gz.sha256
          do
            curl -fsSL https://s3.us-west-2.amazonaws.com/dynamodb-local/$FILENAME -o $FILENAME
          done

          echo "Verifying download......................."
          sha256sum -c dynamodb_local_latest.tar.gz.sha256 || exit 1

          echo "Extracting download archive......................."
          tar -zxf dynamodb_local_latest.tar.gz --directory ./checkout/build
          ls -al ./checkout/build

      - name: Set up test env
        working-directory: .
        run: |-
          echo "${{ github.workspace }}/checkout/build" >> ${{ github.path }}
          cp ./checkout/test/init_test_env.sh ./checkout/build
          cd ./checkout/build
          . init_test_env.sh

      - name: Run the tests
        working-directory: .
        run: |-
          export SLATE_SCHEMA_DIR=${{ github.workspace }}/checkout/resources/api_specification
          export TEST_SRC=${{ github.workspace }}/checkout/test
          
          cd ./checkout/build/tests
          ls -al
