name: Unit Tests

on:
  push:
    branches:
      - feature/250_new-github-workflow-for-api-unit-tests

#  workflow_dispatch:
#    inputs:
#      branch:
#        description: 'Choose a branch to test:'
#        type: choice
#        default: master
#        options:
#          - develop
#          - master
#        required: true

env:
  AWS_CPP_SDK_VERSION: 1.7.345
  HELM_VERSION: 3.8.1
  MINIKUBE_VERSION: 1.24.0
  KUBERNETES_VERSION: v1.23.1
  PYTHON_VERSION: 3.10

jobs:
  build-test:
    name: Build and Test
    runs-on: ubuntu-20.04

    steps:
      - name: Install OS Packages
        run: |-
          sudo apt-get update -y
          sudo apt-get install -y \
            cmake \
            g++ \
            libboost-all-dev \
            libcurl4-openssl-dev \
            libssl-dev \
            libyaml-cpp-dev \
            libz-dev

      - name: Create extra directories
        working-directory: .
        run: |-
          mkdir ./aws

      - name: Download AWS C++ SDK Source
        working-directory: ./aws
        run: |-
          curl -fsSL https://github.com/aws/aws-sdk-cpp/archive/${{ env.AWS_CPP_SDK_VERSION }}.tar.gz -o ${{ env.AWS_CPP_SDK_VERSION }}.tar.gz
          tar -zxf ${{ env.AWS_CPP_SDK_VERSION }}.tar.gz --directory .

      - name: Build and install AWS C++ SDK
        working-directory: ./aws
        run: |-
          mkdir ./build
          cd ./build
          cmake ../aws-sdk-cpp-${{ env.AWS_CPP_SDK_VERSION }} -DBUILD_ONLY="dynamodb;route53" -DBUILD_SHARED_LIBS=Off
          make
          sudo make install

      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./checkout

      - name: Build SLATE binaries
        working-directory: ./checkout/build
        run: |-
          cmake .. -DBUILD_CLIENT=False -DBUILD_SERVER=True -DBUILD_SERVER_TESTS=True -DSTATIC_CLIENT=False
          export VERSION_OVERRIDE=localdev
          make

      - id: minikube
        name: Create Minikube Cluster
        uses: medyagh/setup-minikube@master
        with:
          minikube-version: ${{ env.MINIKUBE_VERSION }}
          driver: docker
          container-runtime: containerd
          kubernetes-version: ${{ env.KUBERNETES_VERSION }}
          cni: calico

      - name: Display Kubeconfig
        working-directory: .
        run: |-
          kubectl config view > kubeconfig
          cat kubeconfig

      - name: Download DynamoDB
        working-directory: .
        run: |-
          echo "Downloading DynamoDB from Amazon......................."
          for FILENAME in dynamodb_local_latest.tar.gz dynamodb_local_latest.tar.gz.sha256
          do
            curl -fsSL https://s3.us-west-2.amazonaws.com/dynamodb-local/$FILENAME -o $FILENAME
          done

          echo "Verifying download......................."
          sha256sum -c dynamodb_local_latest.tar.gz.sha256 || exit 1

          echo "Extracting download archive......................."
          tar -zxf dynamodb_local_latest.tar.gz --directory ./checkout/build
          ls -al ./checkout/build

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Set up tests
        timeout-minutes: 10
        working-directory: ./checkout
        run: |-
          echo "${{ github.workspace }}/checkout/build" >> ${{ github.path }}
          cp ./test/init_test_env.sh ./build
          cd ./build
          . init_test_env.sh

      - name: Run tests
        timeout-minutes: 60
        working-directory: ./checkout/build
        run: |-
          export SLATE_SCHEMA_DIR=${{ github.workspace }}/checkout/resources/api_specification
          export TEST_SRC=${{ github.workspace }}/checkout/test

          ls -al
          make check
