name: Unit Tests
concurrency:
  group: unittests-${{ github.repository }}

on:
  push:
    branches:
      - master
  schedule:
    - cron: '1 22 * * 1-5'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch under test:'
        required: false
        default: develop
        type: string

env:
  AWS_CPP_SDK_CLIENTS: "dynamodb;route53"
  AWS_CPP_SDK_VERSION: "1.9.365"
  DEBIAN_FRONTEND: "noninteractive"
  KUBERNETES_VERSION: "1.24.3"
  HELM_VERSION: "3.8.1"
  MINIKUBE_VERSION: "1.26.1"
  PYTHON_VERSION: "3.10"

jobs:
  workflow-inputs:
    name: Display Workflow Inputs
    runs-on: ubuntu-20.04
    if: github.event.inputs != ''

    steps:
      - name: Output inputs
        run: |-
          echo "## Workflow inputs" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ toJSON(github.event.inputs) }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY

  test:
    name: Test
    runs-on: ubuntu-20.04

    steps:
      - name: Install OS Packages
        run: |-
          sudo apt-get update -y
          sudo apt-get install -y \
          cmake \
          g++ \
          libboost-all-dev \
          libcurl4-openssl-dev \
          libssl-dev \
          libyaml-cpp-dev \
          libz-dev \
          pkg-config

      - name: Install AWS C++ SDK
        working-directory: .
        run: |-
          curl -fsSL https://raw.githubusercontent.com/slateci/docker-images/stable/slate-client-server/scripts/install-aws-cpp-sdk.sh -o install-aws-cpp-sdk.sh
          chmod +x ./install-aws-cpp-sdk.sh
          sudo ./install-aws-cpp-sdk.sh ${{ env.AWS_CPP_SDK_VERSION }} ubuntu20_04

      - name: Check out repo
        if: ${{ github.event.inputs.branch == '' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./checkout

      - name: Check out specific branch of repo
        if: ${{ github.event.inputs.branch != '' }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./checkout
          ref: ${{ github.event.inputs.branch }}

      - name: Build SLATE binaries
        working-directory: ./checkout/build
        run: |-
          cmake .. -DBUILD_CLIENT=True -DBUILD_SERVER=True -DBUILD_SERVER_TESTS=True -DSTATIC_CLIENT=False
          export VERSION_OVERRIDE=localdev
          make

      - id: minikube
        name: Create Minikube Cluster
        uses: medyagh/setup-minikube@master
        with:
          minikube-version: ${{ env.MINIKUBE_VERSION }}
          driver: docker
          container-runtime: containerd
          kubernetes-version: "v${{ env.KUBERNETES_VERSION }}"
          cni: calico

      - name: Display Kubeconfig
        working-directory: .
        run: |-
          kubectl config view > kubeconfig
          cat kubeconfig

      - name: Download DynamoDB
        working-directory: .
        run: |-
          mkdir ./dynamodb
          echo "Downloading DynamoDB from Amazon......................."
          for FILENAME in dynamodb_local_latest.tar.gz dynamodb_local_latest.tar.gz.sha256
          do
            curl -fsSL https://s3.us-west-2.amazonaws.com/dynamodb-local/$FILENAME -o $FILENAME
          done

          echo "Verifying download......................."
          sha256sum -c dynamodb_local_latest.tar.gz.sha256 || exit 1

          echo "Extracting download archive......................."
          tar -zxf dynamodb_local_latest.tar.gz --directory ./dynamodb
          ls -al ./dynamodb

      - name: Install Helm
        uses: azure/setup-helm@v3
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Run tests
        timeout-minutes: 60
        working-directory: ./checkout/build
        env:
          DYNAMODB_JAR: "${{ github.workspace }}/dynamodb/DynamoDBLocal.jar"
          DYNAMODB_LIB: "${{ github.workspace }}/dynamodb/DynamoDBLocal_lib"
          SLATE_SCHEMA_DIR: "${{ github.workspace }}/checkout/resources/api_specification"
          TEST_SRC: "${{ github.workspace }}/checkout/test"
        run: make check

  notifications:
    name: Notifications
    runs-on: ubuntu-20.04
    needs:
      - test
    if: ${{ always() && (needs.build.result == 'failure' || needs.test.result == 'failure') }}

    steps:
      - name: Notify Slack of Failure
        uses: slateci/github-actions/.github/actions/slack-notify-failure@v9
        with:
          slack_bot_token: '${{ secrets.SLACK_NOTIFICATIONS_BOT_TOKEN }}'
