name: Unit Tests

on:
  push:
    branches:
      - feature/250_new-github-workflow-for-api-unit-tests

#  workflow_dispatch:
#    inputs:
#      branch:
#        description: 'Choose a branch to test:'
#        type: choice
#        default: master
#        options:
#          - develop
#          - master
#        required: true

env:
  MINIKUBE_VERSION: 1.24.0
  KUBERNETES_VERSION: v1.23.1
  PYTHON_VERSION: 3.10

jobs:
#  image-build:
#    name: Built Utility Image
#    runs-on: ubuntu-20.04
#
#    steps:
#      - name: Check out repo
#        uses: actions/checkout@v3
#        with:
#          fetch-depth: 1
#          path: .
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#
#      - name: Build Docker image
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: ./resources/docker/clion_remote.Dockerfile
#          outputs: type=docker,dest=/tmp/image.tar
#          target: build-stage
#          push: false
#          tags: clion_remote:${{ github.sha }}
#
#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: image
#          path: /tmp/image.tar
#          retention-days: 1

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-20.04
#    container: asdfasdfasdfasdfasdfasdfasdfasdfasdf
    #    needs:
#      - image-build

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          path: ./checkout

#      - name: Download artifact
#        uses: actions/download-artifact@v3
#        with:
#          name: image
#          path: .
#
#      - name: Load Docker image
#        working-directory: .
#        run: |-
#          docker load --input ./image.tar

#      - name: Set up Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: ${{ inputs.python_version }}
#
#      - name: Install Python packages
#        uses: BSFishy/pip-action@v1
#        with:
#          packages: |
#            jinja2==3.1.2
#            pyyaml==6.0

      - id: minikube
        name: Create Minikube Cluster
        uses: medyagh/setup-minikube@master
        with:
          minikube-version: ${{ env.MINIKUBE_VERSION }}
          driver: docker
          container-runtime: containerd
          kubernetes-version: ${{ env.KUBERNETES_VERSION }}
          cni: calico

      - name: Export Kubeconfig
        working-directory: .
        run: |-
          kubectl config view > Kubeconfig
          cat Kubeconfig

#      - name: Generate Kubeconfig
#        uses: jannekem/run-python-script-action@v1
#        with:
#          script: |
#            import yaml
#            from jinja2 import Environment, FileSystemLoader
#
#            env = Environment(loader = FileSystemLoader('./github/resources/'), trim_blocks=True, lstrip_blocks=True)
#            template = env.get_template('minikube.j2')
#
#            file=open("/home/clionremote/.kube/config", "w")
#            file.write(template.render(
#                  certificate_authority=/home/clionremote/.kube/ca.crt,
#                  client_certificate=/home/clionremote/.kube/client.crt,
#                  client_key=/home/clionremote/.kube/client.key
#                  kubernetes_version=${{ env.KUBERNETES_VERSION }},
#                  server_ip=XXXXXXXXXXXXXXXXXXXXXXXXX))
#            file.close()

#      - name: Download DynamoDB
#        working-directory: ./checkout
#        run: |-
#          echo "Downloading DynamoDB from Amazon......................."
#          for FILENAME in dynamodb_local_latest.tar.gz dynamodb_local_latest.tar.gz.sha256
#          do
#            curl -fsSL https://s3.us-west-2.amazonaws.com/dynamodb-local/$FILENAME -o $FILENAME
#          done
#
#          echo "Verifying download......................."
#          sha256sum -c dynamodb_local_latest.tar.gz.sha256 || exit 1
#
#          echo "Extracting download archive......................."
#          tar xvzf dynamodb_local_latest.tar.gz

#      - name: Start Docker container
#        working-directory: ./checkout
#        run: |-
#          docker run -d \
#            --cap-add sys_ptrace \
#            -p127.0.0.1:2222:22 \
#            -p127.0.0.1:18080:18080 \
#            clion_remote:${{ github.sha }}
